### PR TITLE
Add support for dot syntax between user and group.

### PR DESCRIPTION
**Pull request by vascocosta**

### CODE REVIEW

**Comment by evangreen** [comment]
Hi Vasco. I had never heard of the dot syntax before this pull request! I logged on to my Linux box, and sure enough it works. But there's a little controversy there:
http://serverfault.com/questions/194295/using-dot-as-delimiter-to-specify-group-in-chown

Do the GNU tools go to greater lengths to resolve ambiguities when the user name potentially contains a dot in it? What about more unambiguous cases like myuser.name:mygroup?

As a minor nitpick, you modify the input string. Later in the function we seem to make an effort not to modify the input string, going so far as to make a copy of it. The argument really should be marked PCSTR, but I only recently started using that type.

Was there a particular script that was using this dot syntax, or was it something you knew about because you're used to it?

Perhaps the logic should be something like:
* Look for the colon first. If colon found, done.
* See if the entire string is a valid user name. If it is, use that.
* Look for the last dot. If found, use it as a separator.

**Comment by vascocosta** [comment]
Hi Evan. I'm not using any particular script that assumes dot syntax support, I was simply more used to it on the command line as sysadmin. I still see other sysadmins using both separators quite often.

My "hacky" change was based on the assumption that, for all effects, the period was also a reserved character, just like the colon. I don't ever recall seeing a username with a dot in it.

Having said that, I think it's reasonable to allow it, so I've just committed a change with that in mind. The logic you suggested looks solid and covering all cases.

However, imagine that the user with username evan created a group called green for all his family members. Now suppose there's a second user with the username evan.green. What if the first user issues chown evan.green some_file and chown immediately assumes that he meant the the username evan.green (because now there's a user with that username), when in reality he meant user evan and group green? This is a reason why I'd maybe skip your second point above.

What I basically do with this change is implementing your first and last rules which as a side effect requires the user to explicitly use a trailing dot when using dot notation to mean username like this: chown evan.green. some_file, which by the way mirrors the behavior of chown .groupname. Instead of being "username greedy" I'm being "syntax greedy". Eventually, if we delve deep into this and consider cases where both the username and groupname use multiple dots, then we surely need to enforce the usage of a second separator, like the colon.

Anyway, this was simply meant to address my habit of using dots with chown, so feel totally free to skip this merge request or ask me to check/assume the entire string as a valid username.

**Comment by evangreen** [comment]
Hi Vasco. I think what you're saying makes sense. With this "dot can be either" thing there are going to be ambiguities for sure. I think in these ambiguous cases I'd still prefer to resolve in favor of the future looking direction. That is, not get in the way for somebody who is trying to only change the user name to evan.green, but who also has a username of evan and group of green on their system. The legacy syntax is good, but my feeling is it shouldn't get in the way of someone trying to do something in the new style.

You may also be sick of my comments on this change by now, but I was noticing you might be able to collapse a lot of code down and cut down on duplication by strduping the string unconditionally into a new Copy local, then doing your hunt for both separators (with the '.' one having those conditions) on the copy. It would cut out most of the paragraph you're adding, the conditions around the free, and the second strchr (the one on the newly copied buffer). Not mandatory at all, but a change with more deletes than adds is always a win in my book :)

**Comment by vascocosta** [comment]
Your comments are always helpful and one of the reasons I enjoy Minoca is definitely the quality of the codebase, from which I hope to learn. That duplication I did there looks a bit like spaghetti code to be honest. When I was doing it I realized the repetition, but ended up not cleaning it up.

I also agree with the new trend to use ":" instead of the old separator, especially because it avoids some ambiguity when using usernames with dots. In reality I even use ":" most of the times these days. I guess I came up with this pull request simply because I knew the GNU tools were dealing with the dot, however, after thinking it through, I believe there's not a compelling reason to implement it on Minoca. The way I see it, Minoca is POSIX-like as much as needed and as much as it makes sense, not necessarily regarding legacy stuff that isn't really critical. The same applies in this case and actually enforcing a single separator like the colon makes it clearer.

So yeah, I believe we can close this and I'll instead focus on another piece of code, which I'm sure won't be hard to find. Having said that, just out of curiosity what did you mean by this:

> *See if the entire string is a valid user name. If it is, use that.

Did you mean creating something like `IsValidUsernane`using `getpwnam(UserName)`?

**Comment by vascocosta** [comment]
On second thoughts, wait just a little bit. I think I came up with a reasonable solution today while monkeying around. It still needs more testing though. I'll let you know soon if I commit or eventually close this one.

If nothing else, your input made me learn chown.c from top to bottom, so that's already a net gain there. :)

Just let me know if adding and using a function like this was on your plans or if I got it wrong:

```
BOOL
IsUserNameValid (
    PSTR UserName
    )

{

    if (UserName != NULL) {
        if (isdigit(*UserName) != 0) {
            strtoul(UserName, &AfterScan, 10);
            if (AfterScan == UserName) {
                return FALSE;
            }

        } else {
            UserInformation = getpwnam(UserName);
            if (UserInformation == NULL) {
                return FALSE;
            }

        }
    }

    return TRUE;
}
```

**Comment by evangreen** [comment]
Sorry for the delay, I was travelling yesterday. (Travelling a little today too, but I've got some time this morning to check in!) My internet access might be more sporadic than usual.

My initial thought was just to reuse SwGetUserIdFromName. Something like "If there's no colon, and SwGetUserIdFromName returns failure, find the last dot". SwGetUserIdFromName isn't implemented on Windows, but I don't think any of chown is compiled on Windows.

**Comment by vascocosta** [comment]
Enjoy your holidays, I might be out of reach for a few days as well before Jan 2.

Once you get back take the chance to check my latest commit. Now I respect the current style, so if a valid user name of any sort, including one or multiple dots, is present on the system, chown will take it as such, without trying to parse the group name. Otherwise, it behaves as before if a colon is detected or picks the right-most dot as separator if there are no colons and the user name isn't recognized.

On one hand, I think it makes sense to adopt only the new style which is cleaner, so in other words we could discard this and leave chown as is. On the other hand, I also think about the possibility of legacy scripts that call it with the dot syntax, in which case I think my current version is reasonable and works under all scenarios, unless I forgot to test something. I leave it up to you.

Have fun.

**Comment by evangreen** [comment]
Hi Vasco. I pulled in your changes and made some additional tweaks. Can you review those tweaks and make sure they make sense?

**Comment by vascocosta** [comment]
Hi Evan,

Your changes made the code much cleaner and I couldn't find any bug after testing every possible scenario. This pull request was helpful and the final result achieved the best of both worlds, by adding support to the legacy syntax while keeping the code small and clear, if not clearer than before.

Good job!

I'm closing this one.

**Pull request closed without merging**
