### PR TITLE
Have files in unix file format

### PR DESCRIPTION
**Pull request by jubalh**
Using unix file format instead of dos one.
I excluded the windows specific files from this:
	modified:   apps/debug/client/win32/ui/debugres.rc
	modified:   apps/debug/client/win32/ui/debugui.exe.manifest
	modified:   apps/setup/win32/msetuprc.rc
	modified:   apps/swiss/win32/swiss.exe.manifest
	modified:   apps/swiss/win32/swiss.rc

### CODE REVIEW

**Comment by evangreen** [comment]
These are all Windows-only files. Do you have a corresponding .gitattributes change to ensure that when checked out on Windows with autocrlf these do indeed get CRLFs?

We'd also ask that you electronically sign our contributor agreement at http://www.minocacorp.com/ca/individual/ , which assigns us the copyright to the patch.

**Comment by jubalh** [comment]
The files mentioned above are the files I did **not** add ;)
Did you look at the changes? I think its not Windows-only files.

Ok, I will sign the agreement and also add the .gitattributes file tomorrow.

**Comment by jubalh** [comment]
Some of the files are without file endings, do you really want me to add them to the gitattributes with the whole name then?

**Comment by evangreen** [comment]
Ah, my bad, I was fooled into thinking the files you listed were the files being changed.

Now that I see the actual change I think then you don't need .gitattributes changes. The patch looks fine as is.

**Comment by jubalh** [comment]
Ok :)
Signed.

**Comment by evangreen** [comment]
I rebased this onto master and committed it. Thanks!

**Pull request closed without merging**
